INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Reuniao da empresa', '60 min', 'Itu - SP');
INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Reuniao da escola', '20 min', 'Itu - SP');
INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Medico', '35 min', 'SP');